# Generated by Django 3.1 on 2020-08-31 04:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(default='no_username', max_length=20, unique=True)),
                ('password', models.CharField(default='no_password', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('newsletter', models.BooleanField()),
            ],
        ),
    ]
